// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHpH08oyF423XYRCtOv6BfEb0PK4GOFY0',
    appId: '1:707054387465:web:1a25bcb1523a72c0e393d8',
    messagingSenderId: '707054387465',
    projectId: 'quiz-172e2',
    authDomain: 'quiz-172e2.firebaseapp.com',
    storageBucket: 'quiz-172e2.appspot.com',
    measurementId: 'G-71PZ61RC9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmSpi7LNy9ODVp62RCwpi7bNt2RbN1tVo',
    appId: '1:707054387465:android:7ea89c44fb5096d2e393d8',
    messagingSenderId: '707054387465',
    projectId: 'quiz-172e2',
    storageBucket: 'quiz-172e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi13JOn3oIoijYhAmQup7GwwwE_Fyeebw',
    appId: '1:707054387465:ios:ed3d2e50ec260663e393d8',
    messagingSenderId: '707054387465',
    projectId: 'quiz-172e2',
    storageBucket: 'quiz-172e2.appspot.com',
    iosClientId: '707054387465-0p1lqa209kg8v0bcpah6pt7e71lot11o.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
